# Generated by Django 5.2.17 on 2026-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('speaker', models.CharField(max_length=200)),
                ('sermon_date', models.DateField()),
                ('scripture', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True, help_text='Link to the sermon audio.')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video link.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sermons/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sermon_date', '-created_at'],
            },
        ),
    ]
