# Generated by Django 5.2.17 on 2026-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste the YouTube URL for this sermon.'),
        ),
    ]
